{% set name = "pyb2d" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyb2d/pyb2d/archive/refs/tags/{{ version }}.tar.gz
  sha256: d7cd30da300ea21073f2e9cc715a61f8c26495ff8c57ebbb7109b4dcfe62fc7c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - pybind11
    - numpy
  run:
    - python
    - pydantic
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - b2d
    - b2d.testbed

about:
  home: https://github.com/pyb2d/pyb2d
  license: MIT
  license_family: MIT
  license_file: LICENCE.txt
  summary: Python bindings for Box2D liquidfun
  description: |
    pyb2d is a python wrapper for Box2D and liquidfun
  doc_url: https://github.com/pyb2d/pyb2d
  dev_url: https://github.com/pyb2d/pyb2d

extra:
  recipe-maintainers:
    - DerThorsten
