{% set name = "pyb2d" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyb2d/pyb2d/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2bfb0ff4bda1d41869a664276093060a35c3b35b180f4909d4ce6c9e3aa37068

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - b2d
    - b2d.testbed

about:
  home: https://github.com/pyb2d/pyb2d
  license: MIT
  license_family: MIT
  license_file: LICENCE.txt
  summary: Python bindings for Box2D liquidfun
  description: |
    pyb2d is a python wrapper for Box2D and liquidfun
  doc_url: https://github.com/pyb2d/pyb2d
  dev_url: https://github.com/pyb2d/pyb2d

extra:
  recipe-maintainers:
    - DerThorsten
